name: Download and Upload Icons from Xbox Marketplace

on:
  workflow_dispatch:

jobs:
  download_boxarts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests
          pip install beautifulsoup4

      - name: Run Xbox Marketplace Scraper for Icons
        run: python Scripts/xbox_marketplace_scraper.py
        env:
          BOX_ART_ENV: "Icon"

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Update icons from Xbox Marketplace"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
